// lib/main.dart

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

/// Model class to represent a notification item.
class NotificationItem {
  final String title;
  final String body;
  final String type; // "regular" or "important"
  final DateTime receivedAt;

  NotificationItem({
    required this.title,
    required this.body,
    required this.type,
    required this.receivedAt,
  });
}

/// Top-level background message handler. It must be a top-level function.
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // Initialize Firebase in the background.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  print('Background message received: ${message.notification?.body}');
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using the auto-generated options.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Register background message handler.
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  runApp(MessagingTutorial());
}

class MessagingTutorial extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Firebase Messaging Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(primarySwatch: Colors.blue),
      home: MyHomePage(title: 'Firebase Messaging Demo'),
      // Optionally, you can add routes if you plan to navigate between pages.
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;
  MyHomePage({Key? key, required this.title}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late FirebaseMessaging _messaging;
  // In-memory list to store notification history.
  final List<NotificationItem> _notificationHistory = [];

  @override
  void initState() {
    super.initState();

    // Initialize Firebase Messaging.
    _messaging = FirebaseMessaging.instance;

    // Subscribe to a topic (optional).
    _messaging.subscribeToTopic("messaging");

    // Retrieve and print the FCM token.
    _messaging.getToken().then((token) {
      print("FCM Token: $token");
    });

    // Listen for foreground messages.
    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      print("Foreground message received: ${message.messageId}");

      // Determine the notification type based on the custom data field.
      String type =
          message.data['notificationType']?.toLowerCase() ?? 'regular';

      // Retrieve the title and body from the message.
      String title = message.notification?.title ?? "No Title";
      String body = message.notification?.body ?? "No Body";

      // Create a new NotificationItem and add it to the history.
      final newItem = NotificationItem(
        title: title,
        body: body,
        type: type,
        receivedAt: DateTime.now(),
      );
      setState(() {
        _notificationHistory.add(newItem);
      });

      // Show a customized AlertDialog based on the notification type.
      showDialog(
        context: context,
        builder: (context) {
          return AlertDialog(
            title: Text(
              type == 'important' ? "Important Notification" : "Notification",
              style: TextStyle(
                color: type == 'important' ? Colors.red : Colors.black,
                fontWeight:
                    type == 'important' ? FontWeight.bold : FontWeight.normal,
              ),
            ),
            content: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                // Display an icon based on the notification type.
                Icon(
                  type == 'important' ? Icons.warning : Icons.info,
                  color: type == 'important' ? Colors.red : Colors.blue,
                  size: 48,
                ),
                const SizedBox(height: 16),
                Text(body),
              ],
            ),
            actions: [
              // Dismiss button.
              TextButton(
                onPressed: () {
                  Navigator.of(context).pop();
                },
                child: const Text("OK"),
              ),
              // Navigate to Notification History screen.
              TextButton(
                onPressed: () {
                  Navigator.of(context).pop();
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder:
                          (context) => NotificationHistoryScreen(
                            history: _notificationHistory,
                          ),
                    ),
                  );
                },
                child: const Text("View History"),
              ),
            ],
          );
        },
      );
    });

    // Listen for messages when the user taps on a notification.
    FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
      print("Notification opened: ${message.notification?.body}");
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        actions: [
          // Button to view notification history.
          IconButton(
            icon: const Icon(Icons.history),
            onPressed: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder:
                      (context) => NotificationHistoryScreen(
                        history: _notificationHistory,
                      ),
                ),
              );
            },
          ),
        ],
      ),
      body: const Center(child: Text("Firebase Messaging Demo")),
    );
  }
}

/// A screen to display the notification history.
class NotificationHistoryScreen extends StatelessWidget {
  final List<NotificationItem> history;
  const NotificationHistoryScreen({Key? key, required this.history})
    : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Notification History")),
      body:
          history.isEmpty
              ? const Center(child: Text("No notifications received yet."))
              : ListView.builder(
                itemCount: history.length,
                itemBuilder: (context, index) {
                  final item = history[index];
                  return Card(
                    margin: const EdgeInsets.symmetric(
                      horizontal: 12,
                      vertical: 6,
                    ),
                    child: ListTile(
                      leading: Icon(
                        item.type == 'important' ? Icons.warning : Icons.info,
                        color:
                            item.type == 'important' ? Colors.red : Colors.blue,
                      ),
                      title: Text(item.title),
                      subtitle: Text(item.body),
                      trailing: Text(
                        "${item.receivedAt.hour.toString().padLeft(2, '0')}:${item.receivedAt.minute.toString().padLeft(2, '0')}",
                      ),
                    ),
                  );
                },
              ),
    );
  }
}
